import angularIconParsed from '!!raw-loader!./angular.svg';
import awsIconParsed from '!!raw-loader!./aws.svg';
import bootatrapIconParsed from '!!raw-loader!./bootstrap.svg';
import cplusplusIconParsed from '!!raw-loader!./c++.svg';
import clickHereIconParsed from '!!raw-loader!./click-here.svg';
import cssIconParsed from '!!raw-loader!./css.svg';
import dockerIconParsed from '!!raw-loader!./docker.svg';
import firebaseIconParsed from '!!raw-loader!./firebase.svg';
import gitIconParsed from '!!raw-loader!./git.svg';
import htmlIconParsed from '!!raw-loader!./html.svg';
import jasmineIconParsed from '!!raw-loader!./jasmine.svg';
import jsIconParsed from '!!raw-loader!./js.svg';
import madeInColombiaIconParsed from '!!raw-loader!./made-in-colombia.svg';
import nodeJsIconParsed from '!!raw-loader!./nodejs.svg';
import rxjsIconParsed from '!!raw-loader!./rxjs.svg';
import threeJsIconParsed from '!!raw-loader!./three-js.svg';
import tsIconParsed from '!!raw-loader!./ts.svg';

export const angularIcon = angularIconParsed;
export const awsIcon = awsIconParsed;
export const bootatrapIcon = bootatrapIconParsed;
export const cplusplusIcon = cplusplusIconParsed;
export const clickHereIcon = clickHereIconParsed;
export const cssIcon = cssIconParsed;
export const dockerIcon = dockerIconParsed;
export const firebaseIcon = firebaseIconParsed;
export const gitIcon = gitIconParsed;
export const htmlIcon = htmlIconParsed;
export const jasmineIcon = jasmineIconParsed;
export const jsIcon = jsIconParsed;
export const madeInColombiaIcon = madeInColombiaIconParsed;
export const nodeJsIcon = nodeJsIconParsed;
export const rxjsIcon = rxjsIconParsed;
export const threeJsIcon = threeJsIconParsed;
export const tsIcon = tsIconParsed;